# StackMob 3 created by antiPerson.
# Report issues that you have experienced in the discussion thread.
# If the comments have been removed, see the config.yml file in the defaults folder!

# The size of the area around an entity that should be checked for matching entities to stack with.
check-area:
  x: 7
  y: 4
  z: 7

# Everything related to the tag seen above entities
tag:
  # The delay between updates of the name tag.
  interval: 10
  # The formatting of the tag.
  # Placeholders:
  # %size% - Stack size.
  # %type% - Formatted type name.
  # %bukkit_type% - The entity type as bukkit calls it.
  # Normal Minecraft color codes are also supported, by using '&' before the letter/number.
  format: '&d%size%x &6%type%'
  # If the translations in the entity-lang.yml file should take effect.
  use-translations: false
  # If the tag should be seen when the entity is not hovered over.
  always-visible: true
  # If the stack size if equal to or below this number, don't show the tag.
  remove-at: 1
  # Only show the name tag if the player is near the entity. (requires ProtocolLib)
  show-player-nearby:
    enabled: true
    # Only display the tag to the player if the player is in this area of the entity.
    x: 8
    y: 3
    z: 8


# Custom rules for specific entities.
custom:
# Example (remove hashtags to make this work):
#PIG:
#    stack-max: 25
#    tag:
#        format: '%size%x Piggy'
#        always-visible: true
#        remove-at: 1

# The delay between each time the stacking task is ran (in ticks.)
task-delay: 100
# The maximum size a single stack can be.
stack-max: 5
# If stacked entities should get removed when the chunk unloads.
remove-chunk-unload: true
# Only stack if the entity was spawned by these causes.
# Reasons list can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
stack-reasons:
  -
# Stack only if the entity is one of these types.
# List of the bukkit names can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
stack-types:
  - PIG_ZOMBIE
# If the entity is located in one of these worlds, then stack.
stack-worlds:
  - bskyblock_world
# If the entity was spawned by these causes, then don't stack.
# Reasons list can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
no-stack-reasons:
  -
# Don't stack if the entity is one of these types.
# List of the bukkit names can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
no-stack-types:
  -
# If the entity is located in one of these worlds, then don't stack.
no-stack-worlds:
  -
# Don't stack until there are more than the number specified of entities of the same type in the check area set above.
# Set to 0 to disable this feature.
dont-stack-until: 5

# If specific entities should have a waiting time before their first stack.
# Designed for monster grinders etc.
wait-to-stack:
  enabled: true
  # For (x) times the stack task fires after spawn, don't stack this entity.
  wait-time: 5
  # Entity types that this should work for.
  entity-types:
    - ZOMBIE
    - SKELETON
    - PIG_ZOMBIE
  # Spawn reasons that this should work for.
  spawn-reasons:
    - SPAWNER

# Enables/disables the comparing of mob type specific attributes before stacking together.
compare:
  villager-profession: true
  sheep-wool-sheared: true
  sheep-wool-color: true
  slime-size: true
  horse-color: true
  llama-color: true
  parrot-color: true
  drowned-hand-item: true
  # Applies to more than one type of entity:
  entity-age: true
  can-breed: true
  love-mode: true
  # 1.14 and newer only
  cat-type: true
  mooshroom-variant: true
  fox-type: true

# Check these attributes before stacking.
check:
  tamed: true
  leashed: true
  is-miniature-pet: true
  is-citizens-npc: true

# Things that should be duplicated.
multiply:
  # Make creeper explosions bigger
  creeper-explosion: true
  # Chicken lay eggs, so make more eggs be dropped
  chicken-eggs: true
  # When sheep are sheared, multiply all the wool.
  sheep-wool: false
  # Multiply mushrooms for all of the cows.
  mooshroom-mushrooms: false
  # Multiply the amount of small slimes spawned when a big slime is killed.
  small-slimes: true
  # When an entity is fed it's food, spawn a new stack with the correct number of children.
  breed: false

# If the stack should split into more when these things happen.
divide-on:
  # If sheep should split into separate stacks when sheared.
  sheep-shear: true
  # If dying sheep should cause the stack to split.
  sheep-dye: true
  # When a mooshroom gets sheared, spilt the stack.
  mooshroom-shear: true
  # When a stack is fed it's food, spilt, so the stack can be bred.
  breed: true
  # When a player tames an entity.
  tame: true
  # When an entity it named using a name tag.
  name: true

# Enables the requirement for a permission for use of 'kill-all' or 'kill-step'.
death-type-permission: false

# Increase the player statistics when a mob has a death amount higher than 1.
increase-player-stats: true

# Make every entity die in the stack on death.
kill-all:
  enabled: true
  # DeathEvent reasons that shouldn't trigger kill-all.
  # List of bukkit names for death reasons can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
  reason-blacklist:
    - 'BLOCK_EXPLOSION'
    - 'CONTACT'
    - 'CRAMMING'
    - 'CUSTOM'
    - 'DRAGON_BREATH'
#    - 'DROWNING'
    - 'DRYOUT'
#    - 'ENTITY_ATTACK'
#    - 'ENTITY_EXPLOSION'
#    - 'ENTITY_SWEEP_ATTACK'
#    - 'FALL'
    - 'FALLING_BLOCK'
    - 'FIRE'
    - 'FIRE_TICK'
    - 'FLY_INTO_WALL'
    - 'HOT_FLOOR'
    - 'LAVA'
#    - 'LIGHTNING'
#    - 'MAGIC'
    - 'MELTING'
    - 'POISON'
#    - 'PROJECTILE'
    - 'STARVATION'
    - 'SUFFOCATION'
    - 'SUICIDE'
    - 'THORNS'
#    - 'VOID'
    - 'WITHER'
  # Entity types that shouldn't trigger kill-all.
  type-blacklist:
    - ''

# Only kill some of the stack
kill-step:
  enabled: true
  # DeathEvent reasons that shouldn't trigger kill-step.
  # List of bukkit names for death reasons can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
  reason-blacklist:
    - ''
  # Entity types that shouldn't trigger kill-step.
  type-blacklist:
    - ''
  # The maximum amount by which the stack should decrease by.
  # Setting this to less than 2 will cause errors! If you want entities to be killed on a one-by-one basis, disable both kill-all and kill-step.
  max-step: 5

# Add the leftover damage from the death of one entity onto another, and if the leftover damage could kill another entity the stack will decrease.
kill-step-damage:
  enabled: false
  # DeathEvent reasons that shouldn't trigger kill-step-damage.
  # List of bukkit names for death reasons can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
  reason-blacklist:
    - ''
  # Entity types that shouldn't trigger kill-step-damage.
  type-blacklist:
    - ''

# Multiply the amount of drops depending on the size of the stack killed.
# Only required if kill-all, kill-step or kill-step-damage is enabled above.
multiply-drops:
  enabled: true
  # The amount of entities that the loot should be dropped for in a stack.
  # Useful if there is a high max-stack value, to prevent lag.
  entity-limit: 50
  # If when drops are multiplied, the drops should be compressed to either ingot or block form where applicable.
  compress: true
  # Prevent certain drops from being multiplied.
  drops-blacklist:
    - ''
  # Only drop one item per entity.
  drop-one-per:
    - EMERALD
    - NETHER_STAR
    - TOTEM

# Multiplies the experience dropped on kill-all/kill-step.
multiply-exp:
  enabled: true
  # Algorithms that should be used for multiplying experience.
  # LEGACY - algorithm used in StackMob v2.2.9 and older
  # MINIMAL - only add a small amount of extra experience.
  # NORMAL - the default amount of extra experience.
  # GENEROUS - adds a significant amount of extra experience.
  # CUSTOM - use a custom multiplier for the extra experience.
  # CUSTOM_RANDOM - same as CUSTOM but makes multiplier a bit random.
  algorithm: CUSTOM
  # Used when the CUSTOM or CUSTOM_RANDOM mode is used above.
  custom-multiplier: 1.0

# Multiplies the damage that the player receives.
multiply-damage-done: false

# Multiplies the damage that the entities receives, if multiplied damage is more than the max health, remove stacks.
multiply-damage-received:
  enabled: false
  # Blacklist of damage causes.
  cause-blacklist:
    - ''

# Prevent entities from targeting players.
# Like no-ai but the entities can move.
no-targeting:
  enabled: false
  types-blacklist:
    - ''

# Disables the ai on entities.
no-ai:
  enabled: false
  use-whitelist: false
  types-whitelist:
    - ''

# Add the remaining amount of fire ticks from a dead entity onto the new entity.
fire-ticks:
  enabled: true
  # Blacklist of entity types.
  blacklist:
    - ''

# Everything to do with mcMMO
mcmmo:
  # Give no mcmmo experience
  no-experience:
    enabled: true
    # Blacklist of entity types that should still give mcmmo experience.
    blacklist:
      - ''
mythicmobs:
  # Support for checking of MythicMobs.
  enabled: true
  # MythicMob types that shouldn't stack, use the 'internal name'
  # To prevent all stacking, add 'ALL' to the list below.
  blacklist:
    - ''

# Support for Jobs Reborn by Zrips
jobs-reborn:
  # Support for the for prevention of job rewards.
  enabled: true
  # Entity types that rewards should still be given for.
  blacklist:
    - ''

# If WorldGuard is installed, enable support for it.
# Use the 'entity-stacking' flag to disable mob stacking in certain regions.
worldguard-support: true

# If CustomDrops is installed, use that for mob drops.
custom-drops:
  enabled: true

# The stacking tool which can be obtained using the command '/sm stick'
stack-tool:
  # The material that the stacking tool should use.
  material: STICK

# The caching of entity stack sizes.
storage:
  # The delay between each save of the cache (in seconds.)
  delay: 120
  # The storage method used.
  # FLATFILE = YAML file storage.
  # MYSQL = MySQL database storage - faster but requires a database server.
  type: FLATFILE
  # Database  details
  database:
    # Server details.
    ip: ''
    port: 3306
    # The name of the database you want to use.
    name: ''
    # Login details.
    username: ''
    password: ''